---
  imports:
    - "./color-palette.yml"
  aliases:
    ## Body Color
    COLOR_BG_PRIMARY: "{!PALETTE_GRAPHITE_1}"
    COLOR_BG_SECONDARY: "{!PALETTE_WHITE}"
    COLOR_TEXT: "{!PALETTE_GRAPHITE_10}"

    ## Default Colors
    COLOR_DEFAULT: "{!PALETTE_GRAPHITE_3}"
    COLOR_DEFAULT_ALT: "{!PALETTE_GRAPHITE_1}"
    COLOR_DEFAULT_CONTRAST: "{!PALETTE_GRAPHITE_8}"

    ## Primary Colors
    COLOR_PRIMARY: "{!PALETTE_AZURE_6}"
    COLOR_PRIMARY_ALT: "{!PALETTE_AZURE_7}"
    COLOR_PRIMARY_CONTRAST: "{!PALETTE_WHITE}"

    ## Status Colors
    COLOR_SUCCESS: "{!PALETTE_STATUS_GREEN}"
    COLOR_CAUTION: "{!PALETTE_STATUS_YELLOW}"
    COLOR_WARNING: "{!PALETTE_STATUS_ORANGE}"
    COLOR_DANGER: "{!PALETTE_STATUS_RED}"
    COLOR_MUTED: "{!PALETTE_GRAPHITE_4}"
    COLOR_DISABLED: "{!PALETTE_GRAPHITE_3}"
    COLOR_READONLY: "{!PALETTE_GRAPHITE_2}"
    COLOR_INFO: "{!PALETTE_GRAPHITE_6}"

    ## Form Fields
    DISABLED_OPACITY: "0.5"
    LINE_HEIGHT: "2.2rem"

    ## Borders
    BORDER_RADIUS: "2px"
    BORDER_COLOR: "{!PALETTE_GRAPHITE_4}"
